repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: ['click>=8.0.0']

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        additional_dependencies: ['flake8-bugbear>=23.1.0', 'flake8-comprehensions>=3.10.0']
        language_version: python3
        args:
            - "--ignore=E501"  # Ignore specific rules that conflict with Black


  - repo: https://github.com/ComPWA/pyright-pre-commit
    rev: v1.1.403  # Use latest stable version
    hooks:
      - id: pyright

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.6  # use the latest stable version
    hooks:
      - id: bandit
        args: ["--quiet", "--severity-level", "medium" ]  # optional: silences info-level output

  - repo: local
    hooks:
      - id: django-migrations
        name: Make and apply Django migrations
        entry: bash -c "python manage.py makemigrations && python manage.py migrate"
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: run-tests
        name: Run tests before commit
        entry: python manage.py test
        language: system
        types: [python]
        pass_filenames: false

