alias pm="python manage.py"
alias pms="python manage.py shell"
alias pmr="python manage.py runserver"
alias pmt="python manage.py test"
alias pmc="python manage.py check"
alias pmsm="python manage.py showmigrations"
alias pmmm="python manage.py makemigrations"
alias pmm="python manage.py migrate"
alias pml="python manage.py loaddata"
alias pme="python manage.py dumpdata"
alias pmsq="python manage.py sqlmigrate"
alias pmsql="python manage.py dbshell"

# Miscellaneous aliases
alias pcra="clear && pre-commit run --all-files"
