# Generated by Django 5.2.4 on 2025-07-19 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reviewers',
            field=models.ManyToManyField(
                related_name='reviewed_documents', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='authored_documents',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
